spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
#        http://localhost:8085/client/lastCard -> http://localhost:8085/eureka-config-client-client/lastCard
        - id: eureka-config-client-client
          uri: lb://eureka-config-client-client
          predicates:
#            - 277
#            - Before=2020-03-11T...
#            - After=2020-03-11T...
#            - Header=X-Request-Id, \d+
            - Path=/client/**
            - Method=GET
          filters:
            - RewritePath=/client/(?<path>.*), /$\{path}
        - id: kafka-redis
          uri: lb://kafka-redis
          predicates:
            - Path=/kafka-redis/**
            - Method=GET
          filters:
            - RewritePath=/kafka-redis/(?<path>.*), /$\{path}
    config:
      uri:
        - http://localhost:8082
      fail-fast: false
    compatibility-verifier:
      enabled: false
  config:
    import: configserver:http://localhost:8082

logging:
  level:
    web: DEBUG
#    com.netflix: WARN
    com.titov: DEBUG
management:
  endpoints:
    web:
      exposure:
        include:
          - 'info'
          - 'metric'
          - 'prometheus'
          - 'health'