spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
#        http://localhost:8085/client/lastCard -> http://localhost:8085/eureka-config-client-client/lastCard
        - id: eureka-config-client-client
          uri: lb://eureka-config-client-client
          predicates:
#            - 277
#            - Before=2020-03-11T...
#            - After=2020-03-11T...
#            - Header=X-Request-Id, \d+
            - Path=/client/**
            - Method=GET
          filters:
            - RewritePath=/client/(?<path>.*), /$\{path}
    config:
      uri:
        - http://localhost:8082
      fail-fast: false
  config:
    import: configserver:http://localhost:8082

management:
  endpoints:
    enabled-by-default: true
    web:
#      base-path: /
      exposure:
        include:
          - '*'
  endpoint:
    gateway:
      enabled: true

    health:
      enabled: true
      show-details: always