spring:
  application:
    name: gateway-server
  cloud:
    config:
      uri:
        - http://localhost:8082
      fail-fast: false
  config:
    import: configserver:http://localhost:8082

management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always